/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrendsIndexRouteImport } from './routes/trends/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MealsIndexRouteImport } from './routes/meals/index'
import { Route as TrendsTrendIdRouteImport } from './routes/trends/$trendId'
import { Route as SettingsTandemRouteImport } from './routes/settings/tandem'
import { Route as SettingsPrivacyRouteImport } from './routes/settings/privacy'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsAiRouteImport } from './routes/settings/ai'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as ProfilesNewRouteImport } from './routes/profiles/new'
import { Route as MealsNewRouteImport } from './routes/meals/new'
import { Route as MealsMealIdRouteImport } from './routes/meals/$mealId'
import { Route as GuidesGuideIdRouteImport } from './routes/guides/$guideId'
import { Route as FoodsNewRouteImport } from './routes/foods/new'
import { Route as FoodsAiAnalyzeRouteImport } from './routes/foods/ai-analyze'
import { Route as FoodsFoodIdRouteImport } from './routes/foods/$foodId'
import { Route as ArticlesArticleIdRouteImport } from './routes/articles/$articleId'
import { Route as MealsMealIdEditRouteImport } from './routes/meals/$mealId_.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsIndexRoute = TrendsIndexRouteImport.update({
  id: '/trends/',
  path: '/trends/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const MealsIndexRoute = MealsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MealsRoute,
} as any)
const TrendsTrendIdRoute = TrendsTrendIdRouteImport.update({
  id: '/trends/$trendId',
  path: '/trends/$trendId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTandemRoute = SettingsTandemRouteImport.update({
  id: '/tandem',
  path: '/tandem',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const ProfilesNewRoute = ProfilesNewRouteImport.update({
  id: '/profiles/new',
  path: '/profiles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsNewRoute = MealsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MealsRoute,
} as any)
const MealsMealIdRoute = MealsMealIdRouteImport.update({
  id: '/$mealId',
  path: '/$mealId',
  getParentRoute: () => MealsRoute,
} as any)
const GuidesGuideIdRoute = GuidesGuideIdRouteImport.update({
  id: '/guides/$guideId',
  path: '/guides/$guideId',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsNewRoute = FoodsNewRouteImport.update({
  id: '/foods/new',
  path: '/foods/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsAiAnalyzeRoute = FoodsAiAnalyzeRouteImport.update({
  id: '/foods/ai-analyze',
  path: '/foods/ai-analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodsFoodIdRoute = FoodsFoodIdRouteImport.update({
  id: '/foods/$foodId',
  path: '/foods/$foodId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleIdRoute = ArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsMealIdEditRoute = MealsMealIdEditRouteImport.update({
  id: '/$mealId_/edit',
  path: '/$mealId/edit',
  getParentRoute: () => MealsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/discover': typeof DiscoverRoute
  '/meals': typeof MealsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/pantry': typeof PantryRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRouteWithChildren
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/foods/$foodId': typeof FoodsFoodIdRoute
  '/foods/ai-analyze': typeof FoodsAiAnalyzeRoute
  '/foods/new': typeof FoodsNewRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/meals/$mealId': typeof MealsMealIdRoute
  '/meals/new': typeof MealsNewRoute
  '/profiles/new': typeof ProfilesNewRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/tandem': typeof SettingsTandemRoute
  '/trends/$trendId': typeof TrendsTrendIdRoute
  '/meals/': typeof MealsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/trends': typeof TrendsIndexRoute
  '/meals/$mealId/edit': typeof MealsMealIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/discover': typeof DiscoverRoute
  '/notifications': typeof NotificationsRoute
  '/pantry': typeof PantryRoute
  '/profile': typeof ProfileRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/foods/$foodId': typeof FoodsFoodIdRoute
  '/foods/ai-analyze': typeof FoodsAiAnalyzeRoute
  '/foods/new': typeof FoodsNewRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/meals/$mealId': typeof MealsMealIdRoute
  '/meals/new': typeof MealsNewRoute
  '/profiles/new': typeof ProfilesNewRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/tandem': typeof SettingsTandemRoute
  '/trends/$trendId': typeof TrendsTrendIdRoute
  '/meals': typeof MealsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/trends': typeof TrendsIndexRoute
  '/meals/$mealId/edit': typeof MealsMealIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/discover': typeof DiscoverRoute
  '/meals': typeof MealsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/pantry': typeof PantryRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRouteWithChildren
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/foods/$foodId': typeof FoodsFoodIdRoute
  '/foods/ai-analyze': typeof FoodsAiAnalyzeRoute
  '/foods/new': typeof FoodsNewRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/meals/$mealId': typeof MealsMealIdRoute
  '/meals/new': typeof MealsNewRoute
  '/profiles/new': typeof ProfilesNewRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/tandem': typeof SettingsTandemRoute
  '/trends/$trendId': typeof TrendsTrendIdRoute
  '/meals/': typeof MealsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/trends/': typeof TrendsIndexRoute
  '/meals/$mealId_/edit': typeof MealsMealIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/discover'
    | '/meals'
    | '/notifications'
    | '/pantry'
    | '/profile'
    | '/settings'
    | '/articles/$articleId'
    | '/foods/$foodId'
    | '/foods/ai-analyze'
    | '/foods/new'
    | '/guides/$guideId'
    | '/meals/$mealId'
    | '/meals/new'
    | '/profiles/new'
    | '/settings/about'
    | '/settings/ai'
    | '/settings/data'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/tandem'
    | '/trends/$trendId'
    | '/meals/'
    | '/settings/'
    | '/trends'
    | '/meals/$mealId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/discover'
    | '/notifications'
    | '/pantry'
    | '/profile'
    | '/articles/$articleId'
    | '/foods/$foodId'
    | '/foods/ai-analyze'
    | '/foods/new'
    | '/guides/$guideId'
    | '/meals/$mealId'
    | '/meals/new'
    | '/profiles/new'
    | '/settings/about'
    | '/settings/ai'
    | '/settings/data'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/tandem'
    | '/trends/$trendId'
    | '/meals'
    | '/settings'
    | '/trends'
    | '/meals/$mealId/edit'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/discover'
    | '/meals'
    | '/notifications'
    | '/pantry'
    | '/profile'
    | '/settings'
    | '/articles/$articleId'
    | '/foods/$foodId'
    | '/foods/ai-analyze'
    | '/foods/new'
    | '/guides/$guideId'
    | '/meals/$mealId'
    | '/meals/new'
    | '/profiles/new'
    | '/settings/about'
    | '/settings/ai'
    | '/settings/data'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/tandem'
    | '/trends/$trendId'
    | '/meals/'
    | '/settings/'
    | '/trends/'
    | '/meals/$mealId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  DiscoverRoute: typeof DiscoverRoute
  MealsRoute: typeof MealsRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PantryRoute: typeof PantryRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  ArticlesArticleIdRoute: typeof ArticlesArticleIdRoute
  FoodsFoodIdRoute: typeof FoodsFoodIdRoute
  FoodsAiAnalyzeRoute: typeof FoodsAiAnalyzeRoute
  FoodsNewRoute: typeof FoodsNewRoute
  GuidesGuideIdRoute: typeof GuidesGuideIdRoute
  ProfilesNewRoute: typeof ProfilesNewRoute
  TrendsTrendIdRoute: typeof TrendsTrendIdRoute
  TrendsIndexRoute: typeof TrendsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends/': {
      id: '/trends/'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/meals/': {
      id: '/meals/'
      path: '/'
      fullPath: '/meals/'
      preLoaderRoute: typeof MealsIndexRouteImport
      parentRoute: typeof MealsRoute
    }
    '/trends/$trendId': {
      id: '/trends/$trendId'
      path: '/trends/$trendId'
      fullPath: '/trends/$trendId'
      preLoaderRoute: typeof TrendsTrendIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tandem': {
      id: '/settings/tandem'
      path: '/tandem'
      fullPath: '/settings/tandem'
      preLoaderRoute: typeof SettingsTandemRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/profiles/new': {
      id: '/profiles/new'
      path: '/profiles/new'
      fullPath: '/profiles/new'
      preLoaderRoute: typeof ProfilesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/new': {
      id: '/meals/new'
      path: '/new'
      fullPath: '/meals/new'
      preLoaderRoute: typeof MealsNewRouteImport
      parentRoute: typeof MealsRoute
    }
    '/meals/$mealId': {
      id: '/meals/$mealId'
      path: '/$mealId'
      fullPath: '/meals/$mealId'
      preLoaderRoute: typeof MealsMealIdRouteImport
      parentRoute: typeof MealsRoute
    }
    '/guides/$guideId': {
      id: '/guides/$guideId'
      path: '/guides/$guideId'
      fullPath: '/guides/$guideId'
      preLoaderRoute: typeof GuidesGuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/new': {
      id: '/foods/new'
      path: '/foods/new'
      fullPath: '/foods/new'
      preLoaderRoute: typeof FoodsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/ai-analyze': {
      id: '/foods/ai-analyze'
      path: '/foods/ai-analyze'
      fullPath: '/foods/ai-analyze'
      preLoaderRoute: typeof FoodsAiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foods/$foodId': {
      id: '/foods/$foodId'
      path: '/foods/$foodId'
      fullPath: '/foods/$foodId'
      preLoaderRoute: typeof FoodsFoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleId': {
      id: '/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof ArticlesArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals/$mealId_/edit': {
      id: '/meals/$mealId_/edit'
      path: '/$mealId/edit'
      fullPath: '/meals/$mealId/edit'
      preLoaderRoute: typeof MealsMealIdEditRouteImport
      parentRoute: typeof MealsRoute
    }
  }
}

interface MealsRouteChildren {
  MealsMealIdRoute: typeof MealsMealIdRoute
  MealsNewRoute: typeof MealsNewRoute
  MealsIndexRoute: typeof MealsIndexRoute
  MealsMealIdEditRoute: typeof MealsMealIdEditRoute
}

const MealsRouteChildren: MealsRouteChildren = {
  MealsMealIdRoute: MealsMealIdRoute,
  MealsNewRoute: MealsNewRoute,
  MealsIndexRoute: MealsIndexRoute,
  MealsMealIdEditRoute: MealsMealIdEditRoute,
}

const MealsRouteWithChildren = MealsRoute._addFileChildren(MealsRouteChildren)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAiRoute: typeof SettingsAiRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsTandemRoute: typeof SettingsTandemRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAiRoute: SettingsAiRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsTandemRoute: SettingsTandemRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  DiscoverRoute: DiscoverRoute,
  MealsRoute: MealsRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PantryRoute: PantryRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRouteWithChildren,
  ArticlesArticleIdRoute: ArticlesArticleIdRoute,
  FoodsFoodIdRoute: FoodsFoodIdRoute,
  FoodsAiAnalyzeRoute: FoodsAiAnalyzeRoute,
  FoodsNewRoute: FoodsNewRoute,
  GuidesGuideIdRoute: GuidesGuideIdRoute,
  ProfilesNewRoute: ProfilesNewRoute,
  TrendsTrendIdRoute: TrendsTrendIdRoute,
  TrendsIndexRoute: TrendsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
